site_name: Quattor Configuration Modules (Core)

theme: 'readthedocs'

pages:
- Home: 'index.md'
- Components:
    - 'components/accounts.md'
    - 'components/afsclt.md'
    - 'components/aiiserver.md'
    - 'components/altlogrotate.md'
    - 'components/amandaserver.md'
    - 'components/authconfig.md'
    - 'components/autofs.md'
    - 'components/ccm.md'
    - 'components/cdp.md'
    - 'components/ceph.md'
    - 'components/ceph::commands.md'
    - 'components/ceph::compare.md'
    - 'components/ceph::config.md'
    - 'components/ceph::crushmap.md'
    - 'components/ceph::daemon.md'
    - 'components/chkconfig.md'
    - 'components/cron.md'
    - 'components/cups.md'
    - 'components/directoryservices.md'
    - 'components/dirperm.md'
    - 'components/download.md'
    - 'components/etcservices.md'
    - 'components/filecopy.md'
    - 'components/filesystems.md'
    - 'components/fmonagent.md'
    - 'components/fstab.md'
    - 'components/ganglia.md'
    - 'components/gmetad.md'
    - 'components/gmond.md'
    - 'components/gpfs.md'
    - 'components/grub.md'
    - 'components/hostsaccess.md'
    - 'components/hostsfile.md'
    - 'components/icinga.md'
    - 'components/interactivelimits.md'
    - 'components/ipmi.md'
    - 'components/iptables.md'
    - 'components/ldconf.md'
    - 'components/libvirtd.md'
    - 'components/mcx.md'
    - 'components/metaconfig.md'
    - 'components/modprobe.md'
    - 'components/mysql.md'
    - 'components/nagios.md'
    - 'components/named.md'
    - 'components/network.md'
    - 'components/nfs.md'
    - 'components/nrpe.md'
    - 'components/nsca.md'
    - 'components/nscd.md'
    - 'components/nss.md'
    - 'components/ntpd.md'
    - 'components/ofed.md'
    - 'components/openldap.md'
    - 'components/opennebula.md'
    - 'components/opennebula::commands.md'
    - 'components/openvpn.md'
    - 'components/pam.md'
    - 'components/pnp4nagios.md'
    - 'components/postfix.md'
    - 'components/postgresql.md'
    - 'components/profile.md'
    - 'components/puppet.md'
    - 'components/resolver.md'
    - 'components/sendmail.md'
    - 'components/shorewall.md'
    - 'components/spma.md'
    - 'components/spma::ips.md'
    - 'components/spma::yum.md'
    - 'components/ssh.md'
    - 'components/sudo.md'
    - 'components/symlink.md'
    - 'components/sysconfig.md'
    - 'components/sysctl.md'
    - 'components/syslog.md'
    - 'components/syslogng.md'
    - 'components/systemd.md'
    - 'components/systemd::Service.md'
    - 'components/systemd::Chkconfig.md'
    - 'components/systemd::chkconfig.md'
    - 'components/systemd::Unit.md'
    - 'components/systemd::Systemctl.md'
    - 'components/useraccess.md'
